baseURL: http://chewz.io
languageCode: en-us
title: Chewz - The Best Way to Find Fewd
theme: hugo-fresh
googleAnalytics: UA-148520805-1

params:
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    title: Deciding what to eat was never so easy.
    subtitle: Get the app and start chewzing!
    buttontext: Download beta
    buttonlink: https://mailchi.mp/0e92b7716009/chewz
    # Hero image (from static/images/___)
    image: illustrations/worker1.png
  section1:
    title: Take the work out of chewzing 
    tiles:
    - title: Chewz smarter, not harder
      icon: card3
      text: 50x faster than your normal fewd chewzing experience. 
      url: https://chewz.s3-us-west-1.amazonaws.com/chewz_app.html
      buttonText: Learn how Chewz works
    - title: Chewz with your friends
      icon: card2
      text: You’re busy, so are your friends. Party chewzing!
      url: https://chewz.s3-us-west-1.amazonaws.com/chewz_group.html
      buttonText: Learn how Groups works
    - title: AI + fewd = yummier life 
      icon: card5
      text: Chewz's AI takes food selection to the next level.
      url: https://chewz.s3-us-west-1.amazonaws.com/chewz_science.html
      buttonText: Learn about Chewz Science
  section2: false
  section3: false
  section4:
    title: Everybody Loves Chewzing
    clients:
    - name: 
      quote: Finding good vegan restaurants is hard! Every time you want to try a new dish, you never know what you will get! When I chewz I have access to many more menu pictures! I love it!
      img: 1
    - name: 
      quote: So many options, restaurants, and most of the menus item don't have pictures. Chewz transforms the way you experience eating. It’s no longer a task. It’s straight to the point.
      img: 2
    - name: 
      quote: Every time my friends and I needed to pick what to eat, we used to spend hours trying to decide which restaurant. It was so tiring! Now we are chewzing and having a good time.
      img: 3
  section5: false
  footer:
    socialmedia:
    - link: https://www.facebook.com/pg/Chewz-104710590927719
      icon: facebook
    - link: https://www.linkedin.com/company/chewzapp
      icon: linkedin
    - link: https://github.com/chewzapp
      icon: github
    - link: https://www.instagram.com/letschewz/
      icon: instagram  
    - link: https://twitter.com/letschewz
      icon: twitter    
    quicklinks:
      column1:
        title: Enterprise
        links:
        - text: Learn about Chewz for Restaurants
          link: http://bit.ly/chewz_api_form

