baseURL: http://chewz.io/
languageCode: en-us
title: Chewz
theme: hugo-fresh

params:
  navbarlogo:
   title: Chewz
   link: /
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    title: Chewz
    # Hero subtitle (optional)
    subtitle: Deciding what to eat was never so easy. Download the app and start chewzing!
    # Button text
    buttontext: Download beta 
    # Where the main hero button links to
    buttonlink: "/chewzapp"
    # Hero image (from static/images/___)
    image: illustrations/worker1.png
  navbar:
  - title: Chewz App
    url: /chewzapp
  - title: Chewz API
    url: /chewzapi
  section1: false
  section2: false
  section3: false
  section4:
    title: Everybody is Chewzing!
    clients:
    - name: Tyler Blackman
      quote: Finding good vegan restaurants is hard! Every time you want try a new dish, you never know what you will get! When I chewz I have access to many more pictures! I love it!
      job: Engineer
      img: 1
    - name: Collin Bradley
      quote: So many options, restaurants, and mostly of the menus item don't have pictures. I am busy, ain't nobody have time fo that! Chewz has not only improved my life, but also made me a better person.
      job: Entrepreneur
      img: 2
    - name: Michael Walters
      quote: Every time my friends and I need to pick what to eat, we spend hours trying to come with a restaurant. It's so tiring! With Chewz we now have fun in the process!
      job: Artist
      img: 3
  section5: false
  footer:
    socialmedia:
    - link: https://www.facebook.com/chewzapp/
      icon: facebook
    - link: https://www.linkedin.com/company/chewzapp
      icon: linkedin
    quicklinks:
      column1:
        title: "About Us"
        links:
        - text: Our Story
          link: /ourstory
